// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchCheckKeys(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BatchCheckKeys'](arg1, arg2, arg3, arg4);
}

export function Chat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Chat'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CheckKey'](arg1, arg2, arg3, arg4);
}

export function ClearStartupPass() {
  return window['go']['main']['App']['ClearStartupPass']();
}

export function DecryptAPIKey(arg1) {
  return window['go']['main']['App']['DecryptAPIKey'](arg1);
}

export function ExportEncryptedList() {
  return window['go']['main']['App']['ExportEncryptedList']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetCachedModelResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCachedModelResult'](arg1, arg2, arg3);
}

export function GetDefaultBaseURLs() {
  return window['go']['main']['App']['GetDefaultBaseURLs']();
}

export function GetModelCache() {
  return window['go']['main']['App']['GetModelCache']();
}

export function GetPrompt() {
  return window['go']['main']['App']['GetPrompt']();
}

export function GetProtocols() {
  return window['go']['main']['App']['GetProtocols']();
}

export function GetStartupPassStatus() {
  return window['go']['main']['App']['GetStartupPassStatus']();
}

export function LoadConfigWithPassword(arg1) {
  return window['go']['main']['App']['LoadConfigWithPassword'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveModelCache(arg1) {
  return window['go']['main']['App']['SaveModelCache'](arg1);
}

export function SetPrompt(arg1) {
  return window['go']['main']['App']['SetPrompt'](arg1);
}

export function SetStartupPass(arg1) {
  return window['go']['main']['App']['SetStartupPass'](arg1);
}

export function TestModel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestModel'](arg1, arg2, arg3, arg4, arg5);
}

export function VerifyStartupPass(arg1) {
  return window['go']['main']['App']['VerifyStartupPass'](arg1);
}
