// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {checker} from '../models';
import {appconfig} from '../models';

export function BatchCheckKeys(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:string):Promise<checker.BatchCheckResult>;

export function Chat(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CheckKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<checker.CheckResult>;

export function ClearStartupPass():Promise<void>;

export function DecryptAPIKey(arg1:string):Promise<string>;

export function ExportEncryptedList():Promise<Array<Record<string, string>>>;

export function GetAppConfig():Promise<appconfig.AppConfig>;

export function GetCachedModelResult(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDefaultBaseURLs():Promise<Record<string, string>>;

export function GetModelCache():Promise<appconfig.ModelCache>;

export function GetPrompt():Promise<string>;

export function GetProtocols():Promise<Array<string>>;

export function GetStartupPassStatus():Promise<boolean>;

export function LoadConfigWithPassword(arg1:string):Promise<void>;

export function SaveAppConfig(arg1:appconfig.AppConfig):Promise<appconfig.AppConfig>;

export function SaveModelCache(arg1:appconfig.ModelCache):Promise<void>;

export function SetPrompt(arg1:string):Promise<void>;

export function SetStartupPass(arg1:string):Promise<void>;

export function TestModel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function VerifyStartupPass(arg1:string):Promise<boolean>;
